version: 2
jobs:
    build:
        docker:
            - image: 'node:8.6.0'
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                key: 'yarn-cache-{{ checksum "src/client/yarn.lock" }}'
            - run:
                name: install client dependencies 
                command: yarn install --no-progress
                working_directory: src/client
            - save_cache:
                key: 'yarn-cache-{{ checksum "src/client/yarn.lock" }}'
                paths:
                    - node_modules
            - run:
                name: get coveralls
                command: yarn global add coveralls
                working_directory: src/client
            - run: 
                name: lint, test and report coverage
                command: yarn lint && yarn test && cat ./coverage/lcov.info | coveralls
                working_directory: src/client
            # Deployment suggestion:
            # You can build your assets on CI
            # - run:
            #    name: build client-side assets
            #    command: yarn build
            #    working_directory: src/client
            # You can then change back to server directory
            # Package the app server with Docker and push to registry